import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./components/Providers";
import { Toaster } from "@/components/ui/sonner";
//import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import { QueryProvider } from "@/components/query-provider";
import { SocketProvider } from "./components/socketProvider";

//const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={cn("antialiased min-h-screen")}>
                <Providers>
                    <SocketProvider>
                        <QueryProvider>
                            <NuqsAdapter>
                                <Toaster />
                                {children}
                            </NuqsAdapter>
                        </QueryProvider>
                    </SocketProvider>
                </Providers>
            </body>
        </html>
    );
}
